name: Build app and update Docker image

on:
  push:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=docker_image::netwerk-digitaal-erfgoed/ldwizard-erfgoedwizard/ldwizard-erfgoedwizard"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com

      - name: Build and push image to Docker registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          tags: |
            ${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.sha_short }}
            ${{ steps.vars.outputs.docker_image }}:latest

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Store DigitalOcean credentials
        run: doctl kubernetes cluster kubeconfig save nde

      # See https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment
      - name: Update deployment
        run: |
          kubectl set image deployment/ldwizard-erfgoedwizard ldwizard-erfgoedwizard=${{ steps.vars.outputs.docker_image }}:${{ steps.vars.outputs.sha_short }} --record

      - name: Verify deployment
        run: kubectl rollout status deployment/ldwizard-erfgoedwizard
